// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhZlqFfMxHlXSHlqU1BHlEurHkA814-pY',
    appId: '1:135985282748:web:0a5de37e910d102f321ab9',
    messagingSenderId: '135985282748',
    projectId: 'fitness-project-d124a',
    authDomain: 'fitness-project-d124a.firebaseapp.com',
    storageBucket: 'fitness-project-d124a.appspot.com',
    measurementId: 'G-TW1LKG6EPQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPvT4Tr75xcRSHGBPJl7Us2K8SujRgnyg',
    appId: '1:135985282748:android:0fca37931a69ef7e321ab9',
    messagingSenderId: '135985282748',
    projectId: 'fitness-project-d124a',
    storageBucket: 'fitness-project-d124a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtaX8q9xvevyvq9ha-jl0GM7YzYplq72o',
    appId: '1:135985282748:ios:0a48651c590ab99d321ab9',
    messagingSenderId: '135985282748',
    projectId: 'fitness-project-d124a',
    storageBucket: 'fitness-project-d124a.appspot.com',
    iosClientId: '135985282748-ntd2j9hi58c4rnnhg20d13rognp3hfq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitness',
  );
}
